### ISSUE TITLE
Breaks jest testing framework

### ISSUE THREAD

**Issue by billiegoose** [jessetane/thru#1]
```
  ● Test suite failed to run

    Cannot find module '_stream_transform' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (node_modules/thru/index.js:1:106)
```

The root causes is that npm.im/builtin-modules does not list _stream_transform, because it is not part of the documented node API.

jest-resolve -> is-builtin-module -> builtin-modules

**Comment by billiegoose** [comment]
Closing this and moving to https://github.com/sindresorhus/builtin-modules/issues/2
